[build]
builder = "NIXPACKS"
buildCommand = "cd express-server && npm install && npm run build"

[deploy]
startCommand = "cd express-server && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

